# Debug mode
debug: false

# Training parameters
training:
  epochs: 1
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.0
  gradient_clip_val: 1.0
  num_workers: 4
  pin_memory: true
  log_every_n_steps: 100
  log_dir: "logs"
  checkpoint_dir: "checkpoints"

# Data paths configuration
data:
  context_length: 5
  horizon: 15
  paths:
    data_dir: "/home/maxboels/datasets/CholecT50"
    fold: 0
    metadata_file: "embeddings_f0_swin_bas_129_with_enhanced.csv"
    video_global_outcome_file: null
  risk_score_path: null
  max_videos: 5                     # Set to null to use all videos
  frame_risk_agg: 'max'

# Model configurations
models:
  # GPT-2 model configuration
  world_model:
    hidden_dim: 768
    embedding_dim: 1024
    n_layer: 6
    use_head: true
    targets_dims:
      next_z: 512
      next_a: 100
      next_r: 1
      next_q: 1
      final_R: 1
    target_heads: null  # ["next_a", "next_r", "next_q", "final_R"]
    # Loss weights
    loss_weights:
      w_z: 1.0  # Embedding prediction (default: 0.8)
      w_a: null  # Action prediction (0.2)
      w_r: null  # Reward prediction (0.1)
      w_q: null  # Q-value prediction (0.1)
      w_R: null  # Final reward estimation (0.05)
    eval:
      horizon: 15
  
  # Reward model configuration
  reward:
    input_dim: 1024
    context_length: 5
    hidden_dim: 256
    num_heads: 4
    num_layers: 2

# Experiment settings
experiment:
  max_videos: 5  # Set to null to use all videos