# Debug mode
debug: false
experiment:
  max_videos: null  # Set to null to use all videos
  pretrain_next_frame:
    train: true
    inference: false
  pretrain_reward_model: false
  calculate_action_rewards: false
  train_action_policy: false
  run_tdmpc: false
  analyze_results: false
  run_evaluation: false

# Training parameters
training:
  epochs: 10
  batch_size: 16
  learning_rate: 0.00003 # 0.00003
  scheduler:  # Add a learning rate scheduler
    type: "cosine"
    warmup_steps: 100
  weight_decay: 0.1
  gradient_clip_val: 1.0
  num_workers: 4
  pin_memory: true
  log_every_n_steps: 40
  log_dir: "logs"
  save_checkpoint_every_n_epochs: 2
  checkpoint_dir: "checkpoints"

eval:
  world_model:
    use_memory: false
    max_horizon: 15
    eval_horizons: [1, 3, 5, 10, 15]
    top_ks: [1, 3, 5, 10]

# Data paths configuration
data:
  context_length: 20
  train_shift: 1
  padding_value: 0.0
  max_horizon: 15
  paths:
    data_dir: "/nfs/home/mboels/datasets/CholecT50" # server: "/nfs/home/mboels/datasets/CholecT50", "/home/maxboels/datasets/CholecT50"
    class_labels_file_path: "./data/labels.json"
    fold: 0
    metadata_file: "embeddings_f0_swin_bas_129_with_enhanced.csv"
    video_global_outcome_file: null
  risk_score_path: null
  max_videos: null                     # Set to null to use all videos
  frame_risk_agg: 'max'

# Model configurations
models:
  # GPT-2 model configuration
  world_model:
    hidden_dim: 768
    embedding_dim: 1024
    n_layer: 6
    use_head: true
    targets_dims:
      _z: 512
      _a: 100
      _r: 1
      _q: 1
      _R: 1
    target_heads: ['_a'] # "next_r", "next_q", "final_R"]
    # Loss weights
    loss_weights:
      w_z: 1.0  # Embedding prediction (default: 0.8)
      w_a: 1.0  # Action prediction (default: 0.1)
      w_r: null  # Reward prediction (0.1)
      w_q: null  # Q-value prediction (0.1)
      w_R: null  # Final reward estimation (0.05)
  
  # Reward model configuration
  reward:
    input_dim: 1024
    context_length: 5
    hidden_dim: 256
    num_heads: 4
    num_layers: 2